#!/usr/bin/env python3
"""Phase 3 (Vedant) — STEP 5: traceability documents, indices and the package README.

Consumes the partial manifests emitted by generate_figures.py, generate_diagrams.py
and build_tables.py, plus METRIC_SOURCE_MAP.csv, and writes:

  VISUALIZATION_MANIFEST.csv        every artifact with full metadata
  FIGURE_DATA_AUDIT.md              per-figure number-by-number audit trail
  NOT_GENERATED_REGISTER.md         requested visuals that the data does not support
  ppt_assets/FIGURE_INDEX.md
  ppt_assets/DIAGRAM_INDEX.md
  ppt_assets/SLIDE_MAPPING.md
  README.md
"""
from __future__ import annotations

import csv
import datetime
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common as C  # noqa: E402

PARTIALS = ["figures.csv", "diagrams.csv", "tables.csv"]


def repo_commit() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "HEAD"], cwd=C.REPO_ROOT,
                              capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def load_partials() -> list[dict]:
    rows: list[dict] = []
    for name in PARTIALS:
        p = C.BUILD_STATE / name
        if p.exists():
            rows += C.read_csv(p)
    return rows


def build_manifest(rows: list[dict]) -> None:
    fields = ["artifact_id", "artifact_type", "filename", "ppt_variant", "title", "purpose",
              "metric_contract_csv", "source_artifact", "dataset", "n", "system_model_names",
              "baseline_or_modified", "fresh_or_historical", "evidence_grade", "caveat",
              "generation_script"]
    C.write_csv(C.PKG_DIR / "VISUALIZATION_MANIFEST.csv", fields, rows)
    print(f"  wrote VISUALIZATION_MANIFEST.csv ({len(rows)} artifacts)")


# --------------------------------------------------------------------------
def build_figure_audit(rows: list[dict]) -> None:
    figs = [r for r in rows if r["artifact_type"] == "figure"]
    src = {r["metric_csv"]: r for r in C.read_csv(C.PKG_DIR / "METRIC_SOURCE_MAP.csv")}
    out = [
        "# FIGURE_DATA_AUDIT — every plotted number and where it came from",
        "",
        f"Generated {datetime.date.today().isoformat()} against repository commit `{repo_commit()}`.",
        "",
        "## How to read this document",
        "",
        "This package enforces a two-stage rule so that no number can reach a figure without a",
        "traceable origin:",
        "",
        "1. `scripts/build_metric_tables.py` reads the committed experiment artifacts and writes",
        "   one locked CSV per metric contract into `metrics/`. Every row carries its own",
        "   `source_artifact` column.",
        "2. `scripts/generate_figures.py` opens **only** those CSVs. It never opens an experiment",
        "   artifact directly, so a value that is not in a locked CSV cannot appear in a figure.",
        "",
        "`scripts/validate_package.py` re-checks stage 1 against the source artifacts on every run.",
        "",
        "## Metric contracts",
        "",
    ]
    hdr = ["Metric CSV", "Purpose", "Source artifact(s)", "Dataset", "n", "Freshness",
           "Evidence grade", "Caveat"]
    out.append("| " + " | ".join(hdr) + " |")
    out.append("|" + "|".join("---" for _ in hdr) + "|")
    for r in src.values():
        out.append("| " + " | ".join([
            f"`{r['metric_csv']}`", r["purpose"], r["source_artifact"], r["dataset"], r["n"],
            r["fresh_or_historical"], r["evidence_grade"], r["caveat"]]) + " |")
    out += ["", "## Per-figure audit", ""]
    for r in figs:
        out += [
            f"### {r['artifact_id']} — {r['title']}",
            "",
            f"- **File:** `{r['filename']}` · PPT variant `{r['ppt_variant']}`",
            f"- **Purpose:** {r['purpose']}",
            f"- **Metric contract(s):** {r['metric_contract_csv']}",
            f"- **Source artifact(s):** {r['source_artifact']}",
            f"- **Dataset / n:** {r['dataset']} · n = {r['n']}",
            f"- **System designation:** {r['system_model_names']}",
            f"- **Freshness:** {r['fresh_or_historical']}",
            f"- **Evidence grade:** {r['evidence_grade']}",
            f"- **Caveat printed on the figure:** {r['caveat']}",
            f"- **Generated by:** `{r['generation_script']}`",
            "",
        ]
    out += [
        "## Classification rules applied throughout",
        "",
        "| Class | Meaning | Where it is used |",
        "|---|---|---|",
        "| GOLD | The dataset carries real per-item labels, so accuracy / precision / recall / F1 "
        "are legitimate | GOLD-01 (420 curated items), GOLD-02 (59 synthetic items) |",
        "| METRIC-ONLY | Natural NyayaRAG data with no independent correctness label; only "
        "descriptive and paired-comparative statements are permitted | every natural-data figure |",
        "| BEHAVIOUR | A software invariant asserted by a test; says nothing about accuracy | "
        "F23 component coverage |",
        "| HISTORICAL | Cited from a committed prior-session artifact and NOT re-executed here | "
        "every GPU-dependent correction figure |",
        "| PROVISIONAL | Claude-generated labels, never lawyer-verified | **excluded from this "
        "package entirely** — see NOT_GENERATED_REGISTER.md |",
        "",
        "## Standing prohibitions honoured by every figure in this package",
        "",
        "- No natural-data result is ever called accuracy, precision, recall or F1.",
        "- GOLD and METRIC-ONLY values are never averaged, pooled or plotted as one series.",
        "- Synthetic and natural correction rates are never merged into a single rate (see F19).",
        "- No legal-correctness claim is made anywhere; no lawyer ground truth exists in this "
        "project.",
        "- No additive or interaction effect between the four production levers is asserted; that "
        "experiment does not exist (F16, Grade E).",
        "",
    ]
    (C.PKG_DIR / "FIGURE_DATA_AUDIT.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("  wrote FIGURE_DATA_AUDIT.md")


# --------------------------------------------------------------------------
NOT_GENERATED = [
    ("Accuracy / precision / recall / F1 on natural NyayaRAG data",
     "NOT GENERATED — insufficient/unsupported source data",
     "No natural-data record in this project has an independent correctness label. "
     "`evaluation/metrics/METRIC_DEFINITIONS.md` defines every legitimate natural-data metric "
     "as descriptive or paired-comparative for exactly this reason. Producing an accuracy "
     "figure would require inventing labels."),
    ("Confusion matrix on natural data",
     "NOT GENERATED — insufficient/unsupported source data",
     "A confusion matrix needs a true label per item. Only GOLD-01 and GOLD-02 have one, and "
     "both are already plotted (F04, F05)."),
    ("Quantitative comparison against the RhetoricLLaMA / LegalSeg baseline",
     "NOT GENERATED — not a comparable measurement",
     "Different task (sentence-level rhetorical-role classification), different dataset, "
     "different output space; only a one-row smoke test was ever executed "
     "(`research/baseline/BASELINE.md`), and `comparison_config.json` marks it "
     "`explicitly_out_of_scope`. The relationship is documented structurally instead, in "
     "diagram D14."),
    ("Joint four-lever ablation (all four production levers varied from one common baseline)",
     "NOT GENERATED — the experiment does not exist",
     "`evaluation/ablation/ABLATION_SUMMARY.json` classifies this factor NOT_ISOLABLE / "
     "NOT_EXECUTED. It is shown as Grade E in F16 and T03 rather than being estimated."),
    ("Verifier agreement against lawyer ground truth",
     "NOT GENERATED — no such data exists",
     "`REPOSITORY_MANIFEST.md` §6 records that `lawyer_annotation.jsonl` holds provisional, "
     "Claude-generated labels, not a lawyer's answers. Every agreement number computed against "
     "it (including the counter-signal in `final_metrics.json` "
     "section_E) is PROVISIONAL and is deliberately excluded from this package's figures."),
    ("A single pooled correction success rate across synthetic and natural populations",
     "NOT GENERATED — populations are not comparable",
     "Synthetic stress claims are contradictory by construction; natural claims have no "
     "comparable base rate. F19 exists specifically to show this gap rather than hide it."),
    ("Confidence intervals on the correction shipping rates",
     "NOT GENERATED — n too small to be meaningful",
     "1/56 cumulative and 1/10 targeted. The project's own ablation record reports "
     "'none performed -- sample too small for a meaningful test'; this package does not invent one."),
    ("Fresh GPU re-execution of any experiment for this package",
     "NOT PERFORMED — out of scope by instruction",
     "This package runs no experiments and no GPU work. The GPU rows it displays are the "
     "committed historical values plus the evaluation workspace's own STEP 10 / 10B "
     "reproductions, each labelled as such (F17, F22, T06a)."),
    ("Per-claim evidence-coverage trend over time",
     "NOT GENERATED — the regimes are not a time series",
     "The eleven natural-data regimes in F18 differ in case selection and configuration. "
     "Plotting them as a trend would imply a comparison the sampling does not support."),
    ("Cumulative correction rate (1/56) as a reproducible experiment",
     "SHOWN, BUT MARKED HISTORICAL-ONLY",
     "`evaluation/metrics/GPU_REPRODUCTION_CROSSCHECK.md` classifies it PROTOCOL INSUFFICIENT: "
     "the pooled 56-attempt total has no recoverable single reproduction protocol. It appears "
     "in F13 / F14 / T05a with that status printed, and is never presented as a rate estimate."),
]


def build_not_generated() -> None:
    out = ["# NOT_GENERATED_REGISTER — visuals deliberately withheld", "",
           "Each entry below was considered for this package and is recorded here rather than",
           "produced from data that does not support it.", "",
           "| Requested / expected visual | Status | Why |", "|---|---|---|"]
    for what, status, why in NOT_GENERATED:
        out.append(f"| {what} | **{status}** | {why} |")
    out += ["",
            "## What this means for the presentation",
            "",
            "The strongest honest statement this package supports is:",
            "",
            f"> Against its own pre-2026-08-27 baseline, the modified {C.MODIFIED_NAME} "
            "configuration measurably improves **verifier benchmark performance on labelled "
            "GOLD data** (macro F1 0.749 → 0.968, n = 420, McNemar p = 4.16e-23) and "
            "**observed evidence-retrieval coverage on real natural claims** (63.2% → 70.3%, "
            "n = 209, McNemar p = 3.01e-04, zero regressions), while shipping **0 unsafe "
            "corrections in 122 tested correction attempts**.",
            "",
            "It does **not** support any statement that the modified system is more legally "
            "accurate, because no legal ground truth exists anywhere in this project.",
            ""]
    (C.PKG_DIR / "NOT_GENERATED_REGISTER.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("  wrote NOT_GENERATED_REGISTER.md")


# --------------------------------------------------------------------------
def build_indices(rows: list[dict]) -> None:
    figs = [r for r in rows if r["artifact_type"] == "figure"]
    dias = [r for r in rows if r["artifact_type"] == "diagram"]

    out = ["# FIGURE_INDEX — metric figures", "",
           "Each figure exists twice: `figures/<name>.png` (publication density) and",
           "`ppt_assets/figures/<name>.png` (16:9 landscape, presentation type sizes). Both are",
           "rendered from the same locked CSV by `scripts/generate_figures.py`.", "",
           f"**Baseline:** {C.BASELINE_LABEL_1L}  ",
           f"**Modified:** {C.MODIFIED_LABEL_1L}  ",
           f"**Shared stack:** {C.SHARED_STACK}", ""]
    for r in figs:
        out += [f"### {r['artifact_id']} — {r['title']}", "",
                f"- **File:** `{Path(r['filename']).name}`",
                f"- **Purpose:** {r['purpose']}",
                f"- **Dataset / n:** {r['dataset']} · n = {r['n']}",
                f"- **Systems shown:** {r['system_model_names']}",
                f"- **Status:** {r['fresh_or_historical']} · evidence grade {r['evidence_grade']}",
                f"- **Source:** {r['source_artifact']}",
                f"- **Do not claim:** {r['caveat']}", ""]
    (C.OUT_PPT / "FIGURE_INDEX.md").write_text("\n".join(out) + "\n", encoding="utf-8")

    out = ["# DIAGRAM_INDEX — system and flow diagrams", "",
           "Each diagram exists twice: `diagrams/<name>.png` and",
           "`ppt_assets/diagrams/<name>.png` (16:9 landscape, presentation type sizes).",
           "Every component name, model id, config key and outcome label is read from the",
           "repository's own source; no stage is invented.", ""]
    for r in dias:
        out += [f"### {r['artifact_id']} — {r['title']}", "",
                f"- **File:** `{Path(r['filename']).name}`",
                f"- **Purpose:** {r['purpose']}",
                f"- **Systems shown:** {r['system_model_names']}",
                f"- **Source:** {r['source_artifact']}",
                f"- **Note:** {r['caveat']}", ""]
    (C.OUT_PPT / "DIAGRAM_INDEX.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("  wrote ppt_assets/FIGURE_INDEX.md and DIAGRAM_INDEX.md")


# --------------------------------------------------------------------------
SLIDES = [
    ("1", "Title and framing",
     ["—"],
     "Name both systems exactly: baseline NyayaMind v0 (pre-2026-08-27) vs modified NyayaMind "
     "2026-08-27 production. State up front that this is a configuration A/B on one codebase."),
    ("2", "The problem",
     ["diagrams/D14_reference_baseline_rhetoricllama_out_of_scope.png"],
     "LLMs name statutes that sound plausible but are wrong. Use D14 to close the obvious "
     "question about the LegalSeg baseline before it is asked."),
    ("3", "Baseline architecture",
     ["diagrams/D01_baseline_architecture_nyayamind_v0.png"],
     "Establish what the baseline actually is before showing any number."),
    ("4", "Modified architecture",
     ["diagrams/D02_modified_architecture_nyayamind_production.png"],
     "The highlighted panels are the whole contribution; walk them left to right."),
    ("5", "What changed — one slide",
     ["diagrams/D03_baseline_vs_modified_side_by_side.png"],
     "The single most useful slide in a faculty review. Six of ten stages differ, all by "
     "configuration."),
    ("6", "Complete pipeline",
     ["diagrams/D04_complete_pipeline.png", "diagrams/D13_pipeline_modes_a_b_c.png"],
     "Use D13 only if the audience asks about modes; it prevents confusing modes with systems."),
    ("7", "Headline results",
     ["figures/F01_headline_baseline_vs_modified.png"],
     "State explicitly that the four bars are four different kinds of measurement. Do not read "
     "them as one score."),
    ("8", "Verifier performance on labelled data",
     ["figures/F02_gold01_accuracy_macro_f1.png",
      "figures/F04_gold01_confusion_matrices.png"],
     "This is the only place accuracy language is legitimate. The confusion matrices explain "
     "WHY: 92 true-ENTAILED items answered NEI under a bare premise."),
    ("9", "Where the gain lands",
     ["figures/F03_gold01_per_class_precision_recall_f1.png",
      "diagrams/D07_stage_nli_verification.png"],
     "ENTAILED recall 0.50 → 1.00. Pair with D07 so the mechanism is visible, not just the bar."),
    ("10", "Evidence retrieval on real data",
     ["figures/F06_evidence_coverage_209_paired.png",
      "diagrams/D06_stage_evidence_retrieval.png"],
     "The strongest natural-data result: +7.2 pp, McNemar p = 3.01e-04, zero regressions. Say "
     "'coverage', never 'accuracy'."),
    ("11", "Evidence corpus at scale",
     ["figures/F07_evidence_coverage_588_corpus.png",
      "figures/F24_evidence_pool_composition.png"],
     "59 → 136 usable records, and what that bought at the 588-claim scale."),
    ("12", "What the verifier actually outputs",
     ["figures/F08_verdict_distribution_natural.png",
      "figures/F11_confidence_distribution_588.png"],
     "Descriptive only. This is the honest picture of natural-data behaviour: NEI dominates."),
    ("13", "Premise framing on natural data",
     ["figures/F09_premise_framing_natural_batches.png",
      "figures/F10_natural_147_framing_shift.png"],
     "Retrieval is held constant, so the shift is attributable to framing alone. Say "
     "'more decisive verdicts', not 'more correct claims'."),
    ("14", "Why so many claims find no evidence",
     ["figures/F20_no_evidence_taxonomy.png"],
     "Pre-empts the obvious criticism: a ~140-provision corpus, not a parser defect. Zero "
     "confirmed parser/matcher defects across 797 claims."),
    ("15", "Correction and the safety layer",
     ["diagrams/D09_stage_correction_and_reverification.png",
      "diagrams/D10_stage_scope_and_safety_gate.png"],
     "Lead with the mechanism before the numbers — the gates are the contribution here."),
    ("16", "Correction results, honestly",
     ["figures/F13_correction_funnel.png", "figures/F14_correction_outcomes.png"],
     "Almost every attempt is stopped by a gate. Present 0/5 → 1/10 as directional only."),
    ("17", "Safety observations",
     ["figures/F15_safety_observations.png", "figures/F25_scope_gate_replay.png"],
     "0 unsafe of 122 attempts — an observation on a finite history, not a guarantee."),
    ("18", "The transfer gap",
     ["figures/F19_synthetic_vs_natural_transfer.png"],
     "Show it rather than let a reviewer find it. 72.2% synthetic vs 1.8% natural are not the "
     "same measurement."),
    ("19", "Ablations and evidence strength",
     ["figures/F16_ablation_evidence_strength.png",
      "figures/F12_confidence_threshold_sensitivity.png"],
     "Grade A through E, including the Grade E gap. The threshold was deliberately not tuned."),
    ("20", "Reproducibility",
     ["figures/F22_gpu_reproduction_crosscheck.png",
      "figures/F23_component_test_coverage.png",
      "figures/F17_runtime_resource.png"],
     "Byte-identical reproduction on a second GPU machine; 205/205 tests; realistic runtimes."),
    ("21", "Coverage across every regime",
     ["figures/F18_natural_regimes_coverage.png"],
     "The full spread, never pooled. Use if the audience pushes on generalisation."),
    ("22", "Parser fix (code-level ablation)",
     ["figures/F21_claim_parser_fix_n30.png", "diagrams/D05_stage_claim_parsing.png"],
     "Optional. Keep it separate from the four configuration levers."),
    ("23", "Data flow and provenance",
     ["diagrams/D12_full_data_flow.png", "diagrams/D11_final_answer_assembly.png"],
     "Answers 'how do we know these numbers are real?' — every artifact traces back."),
    ("24", "Limitations",
     ["figures/F19_synthetic_vs_natural_transfer.png"],
     "Read NOT_GENERATED_REGISTER.md aloud if pressed. No lawyer ground truth exists; NLI "
     "verdict is not legal correctness; the corpus is ~140 provisions; correction n is tiny."),
    ("25", "Backup / appendix",
     ["figures/F05_gold02_synthetic_contradiction_detection.png",
      "diagrams/D08_stage_verdict_application.png",
      "tables/T02_baseline_vs_modified_comparison.md",
      "tables/T03_ablation_results.md"],
     "Hold in reserve for detailed questions."),
]


def build_slide_mapping() -> None:
    out = [
        "# SLIDE_MAPPING — suggested faculty presentation order", "",
        "A 25-slide skeleton (roughly a 20-minute talk with 5 minutes of questions). Every asset "
        "named below exists in this package; PPT-optimised 16:9 variants live under "
        "`ppt_assets/figures/` and `ppt_assets/diagrams/` with the same filename.", "",
        f"**Say the system names exactly:** baseline = *{C.BASELINE_NAME}*, modified = "
        f"*{C.MODIFIED_NAME}*. Both run {C.GENERATION_MODEL} and {C.VERIFICATION_MODEL}; only "
        "the configuration differs.", "",
        "| # | Slide | Assets | Speaker note |", "|---|---|---|---|",
    ]
    for num, title, assets, note in SLIDES:
        cells = "<br>".join(f"`{a}`" for a in assets)
        out.append(f"| {num} | {title} | {cells} | {note} |")
    out += [
        "", "## Three sentences to rehearse verbatim", "",
        "1. \"Both systems are the same code and the same two models — "
        f"{C.GENERATION_MODEL} for generation and {C.VERIFICATION_MODEL} for verification. "
        "What changed is four configuration levers.\"",
        "2. \"The accuracy numbers are on a labelled 420-item benchmark. On real case data we "
        "report evidence coverage and verdict distributions, because no correctness label "
        "exists for that data anywhere in this project.\"",
        "3. \"Nothing here is a claim about legal correctness. The verifier reports a small "
        "public NLI model's statistical confidence, and the repository stamps that disclaimer on "
        "every result it produces.\"",
        "", "## Questions to expect, and where the answer lives", "",
        "| Likely question | Asset that answers it |", "|---|---|",
        "| \"Why not compare against the LegalSeg / RhetoricLLaMA baseline?\" | "
        "`diagrams/D14_reference_baseline_rhetoricllama_out_of_scope.png` |",
        "| \"Is 70% coverage good? What is the accuracy?\" | "
        "`figures/F08_verdict_distribution_natural.png` + NOT_GENERATED_REGISTER.md |",
        "| \"Why do so many claims have no evidence?\" | "
        "`figures/F20_no_evidence_taxonomy.png` |",
        "| \"Only one correction ever shipped?\" | `figures/F13_correction_funnel.png`, "
        "`figures/F14_correction_outcomes.png` |",
        "| \"Did you tune the threshold to get these numbers?\" | "
        "`figures/F12_confidence_threshold_sensitivity.png` |",
        "| \"Can anyone else reproduce this?\" | "
        "`figures/F22_gpu_reproduction_crosscheck.png`, `tables/T06a_gpu_reproduction_status.md` |",
        "| \"Which of your four changes actually caused the improvement?\" | "
        "`figures/F16_ablation_evidence_strength.png` — and say plainly that the joint "
        "four-lever experiment does not exist (Grade E) |",
        "",
    ]
    (C.OUT_PPT / "SLIDE_MAPPING.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("  wrote ppt_assets/SLIDE_MAPPING.md")


# --------------------------------------------------------------------------
def build_readme(rows: list[dict]) -> None:
    n_fig = sum(1 for r in rows if r["artifact_type"] == "figure")
    n_dia = sum(1 for r in rows if r["artifact_type"] == "diagram")
    n_tab = sum(1 for r in rows if r["artifact_type"] == "table")
    n_metric = len(C.read_csv(C.PKG_DIR / "METRIC_SOURCE_MAP.csv"))
    out = f"""# Output_phase_3_vedant — mentor / PPT visualisation package

Generated {datetime.date.today().isoformat()} against repository commit `{repo_commit()}`.

A self-contained, fully traceable comparison of this project's **baseline** and **modified**
system configurations, built for faculty review. It contains **{n_fig} metric figures**,
**{n_dia} system diagrams**, **{n_tab} tables** and **{n_metric} locked metric contracts**, each
rendered twice (publication density and 16:9 presentation).

---

## The two systems, named exactly

| | Baseline | Modified |
|---|---|---|
| **Name** | {C.BASELINE_NAME} | {C.MODIFIED_NAME} |
| **Generation model** | `{C.GENERATION_MODEL}` (4-bit {C.QUANT}, greedy) | `{C.GENERATION_MODEL}` (4-bit {C.QUANT}, greedy) |
| **Verification model** | `{C.VERIFICATION_MODEL}` | `{C.VERIFICATION_MODEL}` |
| **Correction model** | `{C.CORRECTION_MODEL}` (reuses the generator) | `{C.CORRECTION_MODEL}` (reuses the generator) |
| **`premise_framing`** | `bare` | `labeled` |
| **`use_evidence_v1`** | `false` — 59 usable records | `true` — 136 usable records |
| **`correction.atomic_scope_check`** | `false` (full-sentence rule) | `"assertion_spans"` |
| **`correction.narrow_reverification_hypothesis`** | `false` | `true` |
| **`verification.confidence_threshold`** | `0.70` | `0.70` (unchanged) |

Both systems execute the **identical pipeline code** in `research/prototype/src/`. This is a
configuration A/B on one project, not a comparison against an external system.

**Where these definitions come from:** the modified column is read live from
`research/prototype/config/prototype.yaml`; the baseline column from
`research/prototype/archive/2026-08-27_presentation/final_comparison/comparison_config.json`
(`"ORIGINAL"`), which the repository's own regression test
`tests/test_premise_framing_production.py::test_shipped_config_can_still_reproduce_every_pre_2026_08_27_committed_output`
pins as still reproducible byte-for-byte.

### What is NOT the baseline

The **RhetoricLLaMA / LegalSeg** reproduction (`{C.RHETORIC_BASE_MODEL}` +
`{C.RHETORIC_ADAPTER}`) is a *different task* — sentence-level rhetorical-role classification —
on a different dataset, and only a one-row smoke test was ever executed. No quantitative
comparison against it is made anywhere in this package. See
`diagrams/D14_reference_baseline_rhetoricllama_out_of_scope.png` and
`NOT_GENERATED_REGISTER.md`.

---

## Directory layout

```
Output_phase_3_vedant/
├── README.md                      this file
├── FIGURE_DATA_AUDIT.md           per-figure number-by-number audit trail
├── METRIC_SOURCE_MAP.csv          every locked metric contract and its source artifact
├── VISUALIZATION_MANIFEST.csv     every figure / diagram / table with full metadata
├── NOT_GENERATED_REGISTER.md      visuals deliberately withheld, and why
├── metrics/                       {n_metric} locked figure-data CSVs (the only input to the figures)
├── figures/                       {n_fig} metric figures, publication density
├── diagrams/                      {n_dia} system and flow diagrams
├── tables/                        {n_tab} tables, CSV + Markdown
├── ppt_assets/
│   ├── figures/                   16:9 variants of every figure
│   ├── diagrams/                  16:9 variants of every diagram
│   ├── FIGURE_INDEX.md
│   ├── DIAGRAM_INDEX.md
│   └── SLIDE_MAPPING.md           suggested 25-slide faculty presentation order
├── validation/                    QC reports, including the pytest log
└── scripts/                       the five build scripts (read-only against the repository)
```

## How traceability is enforced

1. `scripts/build_metric_tables.py` reads the committed experiment artifacts and writes one
   locked CSV per metric contract into `metrics/`. Every row carries a `source_artifact` column.
2. `scripts/generate_figures.py` opens **only** those CSVs — never a source artifact — so a
   number that is not in a locked contract cannot reach a figure.
3. `scripts/build_tables.py` builds every table from the same locked CSVs.
4. `scripts/validate_package.py` re-reads the source artifacts and re-checks each contract value,
   then checks naming, file coverage and the prohibited-claim rules.

Rebuild the whole package with:

```
python scripts/build_metric_tables.py
python scripts/generate_figures.py
python scripts/generate_diagrams.py
python scripts/build_tables.py
python scripts/build_docs.py
python scripts/validate_package.py
```

## What this package does NOT do

- It runs **no experiments** and **no GPU work**. Every GPU-dependent value is a committed
  historical result or the evaluation workspace's own STEP 10 / 10B reproduction, labelled as such.
- It **modifies nothing** outside this directory. `src/`, `tests/`, `config/`, `research/data/`,
  `research/prototype/outputs/` and `research/prototype/evaluation/` are read-only inputs.
- It makes **no legal-correctness claim**. No lawyer ground truth exists anywhere in this
  project, and every natural-data figure states that explicitly.

## Reading rules for every number in here

| Class | Meaning |
|---|---|
| **GOLD** | Real per-item labels exist, so accuracy / precision / recall / F1 are legitimate (GOLD-01, GOLD-02 only). |
| **METRIC-ONLY** | Natural NyayaRAG data with no correctness label. Descriptive and paired-comparative statements only — never accuracy. |
| **BEHAVIOUR** | A software invariant asserted by a test. Says nothing about accuracy. |
| **HISTORICAL** | Cited from a committed prior-session artifact; not re-executed here. |
| **FRESH** | Re-executed or re-derived in the evaluation workspace or in this package. |

Evidence grades A–E follow `evaluation/metrics/EVIDENCE_STRENGTH_MATRIX.csv` and communicate how
well a finding is evidenced (isolation, sample size, statistical support) — **not** effect size.

## Validation status

| Check | Result |
|---|---|
| `scripts/validate_package.py` (27 value re-verifications + coverage, naming, claim and protected-path checks) | **PASS** — 0 failures, 0 warnings (`validation/VALIDATION_REPORT.txt`) |
| `pytest research/prototype/tests/ -q` | **205 passed** (`validation/pytest_research_prototype_tests.txt`) |
| `research/prototype/scripts/run_mvp.py --check` | **All checks passed**, 136 usable evidence records (`validation/run_mvp_check.txt`) |
| 10 existing repository validators under `evaluation/scripts/` | 7 PASS; 3 FAIL on one **pre-existing Windows line-ending artifact**, diagnosed in `validation/EXTERNAL_VALIDATOR_NOTES.md` |
| `git status --porcelain` | one entry only: `?? research/prototype/Output_phase_3_vedant/` — no tracked file modified |

The three external-validator failures are all the same two GOLD fixture files, whose hard-coded
SHA-256 constants are the LF-blob hashes while this checkout materialises them with CRLF
(`core.autocrlf = true`). After CRLF→LF normalisation both hashes match the constants exactly, so
no content differs. Nothing was changed to make a validator pass — see
`validation/EXTERNAL_VALIDATOR_NOTES.md` for the full diagnosis.

## Start here

- One slide that answers "what changed?" → `diagrams/D03_baseline_vs_modified_side_by_side.png`
- One figure that answers "did it help?" → `figures/F01_headline_baseline_vs_modified.png`
- The honest limits → `NOT_GENERATED_REGISTER.md`
- The presentation plan → `ppt_assets/SLIDE_MAPPING.md`
"""
    (C.PKG_DIR / "README.md").write_text(out, encoding="utf-8")
    print("  wrote README.md")


def main():
    rows = load_partials()
    if not rows:
        raise SystemExit("No manifest parts found in scripts/_manifest_parts/ — run "
                         "generate_figures.py, generate_diagrams.py and build_tables.py first.")
    print("Building traceability documents ...")
    build_manifest(rows)
    build_figure_audit(rows)
    build_not_generated()
    build_indices(rows)
    build_slide_mapping()
    build_readme(rows)
    for name in PARTIALS:
        p = C.PKG_DIR / name
        if p.exists():
            p.unlink()
    print("\nDocuments complete.")


if __name__ == "__main__":
    main()
