#!/usr/bin/env python3
"""
Production-path bare-vs-labeled comparison on REAL NyayaRAG natural data.

Mirrors compare_premise_framing_synthetic.py's method exactly, but over the
natural cases instead of the synthetic stress set: the SAME real generated
fields and claims already committed in `run_B_n30.jsonl` (30 docs, 88
claims) and `run_natural_targeted.jsonl` (11 docs, 29 claims) are reused
verbatim -- NOTHING is regenerated by the generator, no new dataset and no
new natural sweep is created. Only the NLI premise framing (bare vs
labeled) and, downstream of that, whether a claim triggers correction,
differs between the two arms.

VERIFICATION is genuinely re-run per arm (same real `pipeline.apply_verification`
production code, same DeBERTa model, same 0.70 threshold, same evidence pool)
so that the ENTAILED/CONTRADICTED/NEI/NO_EVIDENCE distribution and correction
TRIGGER count are trustworthy per framing.

CORRECTION is verification-gated: `pipeline.apply_selective_correction` (the
same real production function) is only invoked, per document, when that
document has at least one claim that trigger, under THAT arm's framing.
With `--with-correction` on the GPU machine this is a genuine Qwen call --
not a re-score of an existing correction -- exactly like the synthetic GPU
run. Without `--with-correction` (CPU-safe default) only trigger counts are
produced, matching compare_premise_framing_synthetic.py's split.

Because bare framing has 0 correction triggers on this natural data (see
natural_reverification_framing.md), the bare arm is expected to attempt 0
corrections; only the labeled arm's corrections are genuinely generated.
That asymmetry is the finding, not a bug in this harness.

Validity gate: each arm's freshly-computed BARE-framing verdicts must
reproduce the verdicts already committed in run_B_n30.jsonl /
run_natural_targeted.jsonl (which were produced under production's bare
default). If they do not, this script's baseline reconstruction has
drifted from the committed record and the comparison is void.

Nothing in outputs/ is overwritten; results go to new, separately-prefixed
files.
"""
from __future__ import annotations

import argparse
import copy
import datetime
import json
import sys
import time
from collections import Counter
from pathlib import Path

_PROTOTYPE_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROTOTYPE_ROOT.parent.parent))
sys.path.insert(0, str(_PROTOTYPE_ROOT))

import yaml

from src import pipeline
from src.data_loader import Case, load_usable_evidence
from src.verifier import (
    NLIVerifier, ENTAILED, CONTRADICTED, NOT_ENOUGH_INFORMATION,
    PREMISE_FRAMING_BARE, PREMISE_FRAMING_LABELED,
)
from src.evidence_matcher import NO_EVIDENCE

SOURCES = [
    ("run_B_n30.jsonl", "n30", None),
    ("run_natural_targeted.jsonl", "targeted_n11", "mode_B"),
]


def load_documents(outputs: Path) -> list[dict]:
    """One entry per committed document, tagged by source. Full claim list
    (matched AND unmatched) is kept, because the correction safety gate
    (`_scope_violation`) must check every unflagged claim, not just the
    evidence-matched ones."""
    docs = []
    for fname, tag, sub in SOURCES:
        path = outputs / fname
        if not path.exists():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            rec = json.loads(line)
            block = rec[sub] if sub else rec
            docs.append({
                "source": tag,
                "document_id": rec["document_id"],
                "case_text": block["case_text"],
                "generated_field_text": block["generated_field"]["text"],
                "claims_committed": block["claims"],
            })
    return docs


def build_baseline(doc: dict, by_key: dict) -> dict:
    claim_records = []
    for c in doc["claims_committed"]:
        ev = by_key.get(c["evidence_id"]) if c.get("evidence_id") else None
        claim_records.append({
            "claim_id": c["claim_id"],
            "claim_text": c["claim_text"],
            "citation_extracted": c.get("citation_extracted"),
            "evidence_id": c.get("evidence_id"),
            "evidence_text": c.get("evidence_text"),
            "evidence_match_method": c.get("evidence_match_method"),
            "_evidence_provision": {
                "provision_type": ev.provision_type,
                "provision_number": ev.provision_number,
                "act": ev.act,
            } if ev is not None else None,
            "verdict": NO_EVIDENCE if not c.get("evidence_text") else NOT_ENOUGH_INFORMATION,
            "confidence": None, "sub_reason": None, "verifier_model": None,
        })
    return {
        "document_id": doc["document_id"],
        "case_text": doc["case_text"],
        "generated_field": {"text": doc["generated_field_text"]},
        "claims": claim_records,
    }


def triggers_correction(rec: dict) -> bool:
    """Same trigger condition production uses (pipeline._should_trigger_correction),
    duplicated here for read-only inspection before deciding whether to call the
    real correction function."""
    return rec["verdict"] == CONTRADICTED or rec.get("sub_reason") == "low_confidence"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cpu", choices=["cpu", "cuda"])
    ap.add_argument("--with-correction", action="store_true",
                     help="GPU only: also run the real Qwen corrector and re-verification")
    ap.add_argument("--out-prefix", default="framing_comparison_natural")
    args = ap.parse_args()

    config = yaml.safe_load((_PROTOTYPE_ROOT / "config" / "prototype.yaml").read_text(encoding="utf-8"))
    repo_root = _PROTOTYPE_ROOT.parent.parent
    outputs = _PROTOTYPE_ROOT / "outputs"

    exact_index, all_usable = load_usable_evidence(
        repo_root / config["paths"]["canonical_statutes"],
        repo_root / config["paths"]["evidence_audit"],
        set(config["usable_evidence_verdicts"]),
    )
    by_key = {r.dataset_citation_key: r for r in all_usable}

    documents = load_documents(outputs)
    n_claims = sum(len(d["claims_committed"]) for d in documents)
    n_matched = sum(1 for d in documents for c in d["claims_committed"] if c.get("evidence_text"))
    print(f"Natural documents: {len(documents)}  (claims: {n_claims}, evidence-matched: {n_matched})",
          flush=True)

    generator = corrector = None
    vram_available = False
    if args.with_correction:
        import torch
        if not torch.cuda.is_available():
            print("ERROR: --with-correction requires CUDA. Refusing to run the 7B "
                  "corrector on CPU.", file=sys.stderr)
            return 2
        vram_available = True
        torch.cuda.reset_peak_memory_stats()
        from src.generator import StatuteGroundingGenerator
        from src.corrector import SelectiveCorrector
        generator = StatuteGroundingGenerator(
            model_id=config["generation"]["model_id"],
            quantization=config["generation"]["quantization"],
            device_map=config["generation"]["device_map"],
            max_new_tokens=config["generation"]["max_new_tokens"],
            do_sample=config["generation"]["do_sample"],
            temperature=config["generation"]["temperature"],
            top_p=config["generation"]["top_p"],
            system_prompt=config["generation"]["system_prompt"],
            user_prompt_template=config["generation"]["user_prompt_template"],
            seed=config["seed"],
        )
        generator.load()
        corrector = SelectiveCorrector(
            generator=generator,
            max_new_tokens=config["correction"]["max_new_tokens"],
            do_sample=config["correction"]["do_sample"],
            system_prompt=config["correction"]["system_prompt"],
        )

    verifier = NLIVerifier(
        model_id=config["verification"]["model_id"],
        confidence_threshold=config["verification"]["confidence_threshold"],
        max_sequence_length=config["verification"]["max_sequence_length"],
        device=args.device,
    )
    verifier.load()
    print(f"Loaded {verifier.model_id} on {args.device}", flush=True)

    per_framing: dict[str, dict] = {}
    claim_rows: list[dict] = []
    correction_rows: list[dict] = []

    for framing in (PREMISE_FRAMING_BARE, PREMISE_FRAMING_LABELED):
        arm_config = copy.deepcopy(config)
        arm_config["verification"]["premise_framing"] = framing

        verdicts = Counter()
        triggers = 0
        corr_status = Counter()
        reverif = Counter()
        unsafe_shipped = 0
        unflagged_preserved = 0
        unflagged_checked = 0
        verification_seconds = 0.0
        correction_seconds = 0.0
        arm_t0 = time.time()

        for doc in documents:
            baseline = build_baseline(doc, by_key)
            baseline["_exact_index"] = exact_index
            baseline["_all_usable"] = all_usable
            baseline["_verifier"] = verifier

            t_v0 = time.time()
            pipeline.apply_verification(baseline, verifier, framing)
            verification_seconds += time.time() - t_v0

            doc_triggered = False
            for rec in baseline["claims"]:
                verdicts[rec["verdict"]] += 1
                claim_rows.append({
                    "framing": framing, "source": doc["source"],
                    "document_id": doc["document_id"], "claim_id": rec["claim_id"],
                    "claim_text": rec["claim_text"], "evidence_id": rec["evidence_id"],
                    "evidence_text": rec["evidence_text"],
                    "verdict": rec["verdict"], "confidence": rec["confidence"],
                    "sub_reason": rec["sub_reason"],
                })
                if rec["evidence_text"] is not None and triggers_correction(rec):
                    doc_triggered = True

            if doc_triggered:
                triggers += 1  # documents with >=1 triggering claim; only 1st is attempted

            if args.with_correction and doc_triggered:
                case_obj = Case(document_id=doc["document_id"], case_text=doc["case_text"],
                                 raw_citation_keys=[])
                t_c0 = time.time()
                summary = pipeline.apply_selective_correction(
                    baseline, case_obj, corrector, arm_config
                )
                correction_seconds += time.time() - t_c0
                corr_status[summary["status"]] += 1
                rv = summary.get("reverification") or {}
                if rv.get("verdict"):
                    reverif[rv["verdict"]] += 1
                if summary["status"] == "corrected" and rv.get("verdict") != ENTAILED:
                    unsafe_shipped += 1

                target_id = summary["triggered_for_claim_id"]
                if summary.get("regenerated_text") is not None:
                    for rec in baseline["claims"]:
                        if rec["claim_id"] == target_id:
                            continue
                        unflagged_checked += 1
                        if rec["claim_text"] in summary["regenerated_text"]:
                            unflagged_preserved += 1

                correction_rows.append({
                    "framing": framing, "source": doc["source"],
                    "document_id": doc["document_id"],
                    "triggered_for_claim_id": target_id,
                    "status": summary["status"],
                    "original_field_text": summary["original_field_text"],
                    "regenerated_text": summary["regenerated_text"],
                    "reverification": rv,
                })

        arm_elapsed = time.time() - arm_t0
        arm_peak_vram_mib = None
        if vram_available:
            import torch
            torch.cuda.synchronize()
            arm_peak_vram_mib = torch.cuda.max_memory_allocated() // (1024 * 1024)

        correction_attempts = sum(corr_status.values())
        per_framing[framing] = {
            "n_documents": len(documents),
            "n_claims": n_claims,
            "n_claims_evidence_matched": n_matched,
            "verdict_counts": dict(verdicts),
            "documents_with_trigger": triggers,
            "correction_attempts": correction_attempts,
            "correction_statuses": dict(corr_status),
            "corrections_shipped_success": corr_status.get("corrected", 0),
            "correction_failed": corr_status.get("correction_failed", 0),
            "correction_scope_violation": corr_status.get("correction_scope_violation", 0),
            "reverification_verdicts": dict(reverif),
            "unsafe_corrections_shipped": unsafe_shipped,
            "unflagged_claim_checked": unflagged_checked,
            "unflagged_claim_preserved": unflagged_preserved,
            "correction_ran": args.with_correction,
            "runtime_seconds_total_arm": arm_elapsed,
            "runtime_seconds_verification": verification_seconds,
            "runtime_seconds_correction": correction_seconds,
            "peak_vram_mib_cumulative": arm_peak_vram_mib,
        }
        print(f"[{framing}] verdicts={dict(verdicts)} doc_triggers={triggers} "
              f"correction_attempts={correction_attempts} elapsed={arm_elapsed:.1f}s "
              f"peak_vram={arm_peak_vram_mib}MiB", flush=True)

    # ---- validity gate: bare arm must reproduce the committed natural runs --
    committed_verdicts = {}
    for doc in documents:
        for c in doc["claims_committed"]:
            if c.get("evidence_text") is not None:
                key = (doc["source"], doc["document_id"], c["claim_id"])
                committed_verdicts[key] = c["verdict"]

    bare_rows = {
        (r["source"], r["document_id"], r["claim_id"]): r
        for r in claim_rows
        if r["framing"] == PREMISE_FRAMING_BARE and r["evidence_text"] is not None
    }
    common = sorted(set(committed_verdicts) & set(bare_rows))
    agree = sum(1 for k in common if committed_verdicts[k] == bare_rows[k]["verdict"])
    reproduction = {
        "checked": True, "compared": len(common), "agree": agree,
        "match": agree == len(common) and len(common) > 0,
    }
    print(f"\nBare-arm reproduction of committed natural verdicts: {agree}/{len(common)}", flush=True)

    overall_peak_vram_mib = None
    if vram_available:
        import torch
        torch.cuda.synchronize()
        overall_peak_vram_mib = torch.cuda.max_memory_allocated() // (1024 * 1024)

    result = {
        "experiment": "premise_framing_ablation_natural",
        "data": "NATURAL NyayaRAG generations — run_B_n30.jsonl + run_natural_targeted.jsonl, reused verbatim",
        "verifier_model": verifier.model_id,
        "confidence_threshold": verifier.confidence_threshold,
        "device": args.device,
        "correction_ran": args.with_correction,
        "n_documents": len(documents),
        "n_claims": n_claims,
        "n_claims_evidence_matched": n_matched,
        "seed": config["seed"],
        "bare_arm_reproduction": reproduction,
        "per_framing": per_framing,
        "overall_peak_vram_mib": overall_peak_vram_mib,
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    }
    (outputs / f"{args.out_prefix}_metrics.json").write_text(
        json.dumps(result, indent=2), encoding="utf-8")
    with (outputs / f"{args.out_prefix}_claims_results.jsonl").open("w", encoding="utf-8") as f:
        for r in claim_rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    with (outputs / f"{args.out_prefix}_corrections_results.jsonl").open("w", encoding="utf-8") as f:
        for r in correction_rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    b, l = per_framing[PREMISE_FRAMING_BARE], per_framing[PREMISE_FRAMING_LABELED]
    print("\n" + "=" * 68)
    print(f"{'metric':<40}{'bare':>12}{'labeled':>14}")
    print("-" * 68)
    print(f"{'verdict counts':<40}{str(b['verdict_counts']):>12}{str(l['verdict_counts']):>14}")
    print(f"{'documents with correction trigger':<40}{b['documents_with_trigger']:>12}{l['documents_with_trigger']:>14}")
    if args.with_correction:
        print(f"{'correction attempts':<40}{b['correction_attempts']:>12}{l['correction_attempts']:>14}")
        print(f"{'corrections shipped (SUCCESS)':<40}{b['corrections_shipped_success']:>12}{l['corrections_shipped_success']:>14}")
        print(f"{'correction_failed':<40}{b['correction_failed']:>12}{l['correction_failed']:>14}")
        print(f"{'correction_scope_violation':<40}{b['correction_scope_violation']:>12}{l['correction_scope_violation']:>14}")
        print(f"{'unsafe corrections shipped':<40}{b['unsafe_corrections_shipped']:>12}{l['unsafe_corrections_shipped']:>14}")
        print(f"{'unflagged-claim preserved/checked':<40}"
              f"{str(b['unflagged_claim_preserved'])+'/'+str(b['unflagged_claim_checked']):>12}"
              f"{str(l['unflagged_claim_preserved'])+'/'+str(l['unflagged_claim_checked']):>14}")
        print(f"{'peak VRAM MiB (cumulative)':<40}{str(b['peak_vram_mib_cumulative']):>12}{str(l['peak_vram_mib_cumulative']):>14}")
    print("=" * 68)
    print(f"\nWrote {outputs / (args.out_prefix + '_metrics.json')}")
    print(f"Wrote {outputs / (args.out_prefix + '_claims_results.jsonl')}")
    print(f"Wrote {outputs / (args.out_prefix + '_corrections_results.jsonl')}")

    if reproduction.get("checked") and not reproduction.get("match"):
        print("\nERROR: bare arm did not reproduce committed natural verdicts; "
              "baseline reconstruction has drifted and this comparison is void.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
