#!/usr/bin/env python3
"""
Root-cause taxonomy for NO_EVIDENCE claims on real NyayaRAG n=30 generations.

IMPORTANT: this script re-extracts claims from the same committed
`generated_field.text` in `run_A_n30.jsonl` using the CURRENT (un-modified
by this script) `src/claim_parser.py` and `src/evidence_matcher.py` — NOT
the stale `citation_extracted`/`evidence_id` values already stored in that
file. Investigation for this task discovered that `run_A_n30.jsonl` (and
`run_B_n30.jsonl`, `run_natural_targeted.jsonl`) were generated by an OLDER
parser: `scripts/reparse_n30_with_fixed_parser.py` (pre-existing in this
repo, not written for this task) already shows the CURRENT parser resolves
16 more evidence matches on the exact same generated text (38/88 -> 54/93
claims; extract_claims() also now emits 5 more claim records total, from
citations the old parser dropped or mis-split). Diagnosing the STALE
50/88 figure would misattribute bugs that are already fixed in `src/` but
never propagated to the committed evaluation snapshot. This script instead
diagnoses the CURRENT, real gap: what's left after that already-existing
fix.

READ-ONLY. Nothing in outputs/ (besides this script's own new output file)
or research/data/evidence/ is modified. run_A_n30.jsonl is read but not
written.

Taxonomy (see research_phase_next_status.md for the write-up):
  A. genuinely absent from the 59-record corpus (right act, but that exact
     provision isn't in the audited pool; or the Act/edition itself isn't
     covered — e.g. a different Act altogether, or the same Act under a
     different year/edition)
  B. citation parser failed — act_raw/provision_number is visibly mangled
     relative to the sentence, in a way source code does not yet handle
  C. Act normalization failed — act_norm is a near-miss of a corpus act's
     normalized name that normalize_act()/its alias table doesn't catch
  D. provision extraction failed — number/subsection wrong, act fine
  E. evidence exists (right act AND right provision number) but fuzzy
     act-name token overlap fell short of the 0.8 threshold
  F. claim is genuinely too coarse / multi-citation to safely resolve an
     act for (same provision number resolves to >=2 different acts
     elsewhere in the same field; the parser correctly declined to guess)

A, E, F are mechanically decidable from the corpus + citation dict alone
and are auto-classified with certainty. Everything else is printed under
"NEEDS MANUAL REVIEW" for a human read (this script does not guess B vs C
vs D).
"""
from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

_PROTOTYPE_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROTOTYPE_ROOT.parent.parent))
sys.path.insert(0, str(_PROTOTYPE_ROOT))

import yaml

from src.claim_parser import extract_claims, act_significant_words
from src.data_loader import load_usable_evidence
from src.evidence_matcher import match_evidence, _token_overlap


def main() -> int:
    config = yaml.safe_load((_PROTOTYPE_ROOT / "config" / "prototype.yaml").read_text(encoding="utf-8"))
    repo_root = _PROTOTYPE_ROOT.parent.parent
    outputs = _PROTOTYPE_ROOT / "outputs"
    fuzzy_threshold = config["evidence_matching"]["fuzzy_token_overlap_threshold"]

    exact_index, all_usable = load_usable_evidence(
        repo_root / config["paths"]["canonical_statutes"],
        repo_root / config["paths"]["evidence_audit"],
        set(config["usable_evidence_verdicts"]),
    )
    corpus_acts = sorted(set(e.act_norm for e in all_usable))
    corpus_numbers_by_act = defaultdict(set)
    for e in all_usable:
        corpus_numbers_by_act[e.act_norm].add((e.provision_type, e.provision_number))

    docs_raw = [json.loads(l) for l in (outputs / "run_A_n30.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]

    total_claims = 0
    total_matched = 0
    no_evidence_rows = []
    same_number_acts_by_doc: dict[str, dict] = {}

    # Pass 1: re-extract + re-match every document with the CURRENT parser,
    # to build the same-number/multiple-acts-in-one-field table (F).
    doc_claims: dict[str, list] = {}
    for doc in docs_raw:
        claims = extract_claims(doc["generated_field"]["text"])
        doc_claims[doc["document_id"]] = claims
        m = defaultdict(set)
        for c in claims:
            cit = c.citation_extracted
            if cit and cit.act_norm:
                m[(cit.provision_type, cit.provision_number)].add(cit.act_norm)
        same_number_acts_by_doc[doc["document_id"]] = m

    # Pass 2: classify.
    for doc in docs_raw:
        doc_id = doc["document_id"]
        for claim in doc_claims[doc_id]:
            total_claims += 1
            cit = claim.citation_extracted
            match = match_evidence(cit, exact_index, all_usable, fuzzy_threshold)
            if match.matched:
                total_matched += 1
                continue

            ptype, pnum, sub, act_raw, act_norm = (
                cit.provision_type, cit.provision_number, cit.subsection, cit.act_raw, cit.act_norm,
            )
            row = {
                "document_id": doc_id, "claim_id": claim.claim_id,
                "claim_text": claim.claim_text,
                "citation_extracted": cit.as_dict(),
            }

            if not act_norm:
                same_number_acts = same_number_acts_by_doc[doc_id].get((ptype, pnum), set())
                if len(same_number_acts) >= 2:
                    row["bucket"] = "F"
                    row["reason"] = (f"unresolved act_norm; ({ptype} {pnum}) resolves to "
                                      f"{sorted(same_number_acts)} elsewhere in the SAME document — "
                                      f"genuinely ambiguous, field-wide inheritance correctly declined")
                else:
                    row["bucket"] = "NEEDS_REVIEW"
                    row["reason"] = "unresolved act_norm, not an ambiguous multi-act case — needs manual read"
                no_evidence_rows.append(row)
                continue

            # Candidates sharing this EXACT provision number, regardless of act
            # (this is what actually determines whether fuzzy-matching had any
            # chance to succeed — matching by act-name similarity alone, as an
            # earlier draft of this script did, is misleading: two acts can be
            # textually similar while the corpus simply lacks that section
            # under either one).
            same_number_candidates = [
                e for e in all_usable if e.provision_type == ptype and e.provision_number == pnum
            ]
            if not same_number_candidates:
                row["bucket"] = "A"
                row["reason"] = f"no corpus record has {ptype} {pnum} under ANY act — genuinely absent"
                no_evidence_rows.append(row)
                continue

            claim_words = act_significant_words(act_norm)
            best_ev, best_overlap = None, 0.0
            for e in same_number_candidates:
                ov = _token_overlap(claim_words, act_significant_words(e.act_norm))
                if ov > best_overlap:
                    best_overlap, best_ev = ov, e

            # A "near miss" (E — the matcher's threshold is the blocker) needs
            # meaningfully overlapping act names, not just >0 shared tokens by
            # chance (e.g. "code" appearing in both "Indian Penal Code" and
            # "Code of Criminal Procedure" gives spurious overlap between two
            # UNRELATED acts). 0.5 is a deliberately conservative midpoint:
            # well below the 0.8 production threshold (so real near-misses
            # like a dropped year or an "is applicable" trimming artifact
            # still count as E) but well above stray single-word overlap
            # between genuinely different acts (which is A).
            if best_overlap >= fuzzy_threshold:
                row["bucket"] = "NEEDS_REVIEW"
                row["reason"] = (f"UNEXPECTED: {ptype} {pnum} under {best_ev.act_norm!r} has overlap "
                                  f"{best_overlap:.2f} >= threshold {fuzzy_threshold} yet match_evidence() "
                                  f"still returned NO_EVIDENCE — needs manual read (possible subsection bug)")
            elif best_overlap >= 0.5:
                row["bucket"] = "E"
                row["reason"] = (f"{ptype} {pnum} exists under corpus act {best_ev.act_norm!r} "
                                  f"(claim's act_norm={act_norm!r}); token overlap {best_overlap:.2f} "
                                  f"fell short of the {fuzzy_threshold} fuzzy threshold")
            else:
                row["bucket"] = "A"
                row["reason"] = (f"{ptype} {pnum} exists in corpus only under {[e.act_norm for e in same_number_candidates]}, "
                                  f"only {best_overlap:.2f} act-name overlap with claim's act_norm={act_norm!r} "
                                  f"— different Act, not a normalization near-miss")
            no_evidence_rows.append(row)

    counts = Counter(r["bucket"] for r in no_evidence_rows)
    print(f"Re-extracted claims (current parser): {total_claims}, matched: {total_matched}, "
          f"NO_EVIDENCE: {len(no_evidence_rows)}")
    print(f"Auto-classified buckets: {dict(counts)}")
    print()

    out = {
        "total_claims_current_parser": total_claims,
        "total_matched_current_parser": total_matched,
        "n_no_evidence": len(no_evidence_rows),
        "bucket_counts": dict(counts),
        "corpus_acts": corpus_acts,
        "rows": no_evidence_rows,
    }
    (outputs / "no_evidence_diagnosis.json").write_text(json.dumps(out, indent=2), encoding="utf-8")

    print("=" * 78)
    print("NEEDS MANUAL REVIEW (B/C/D candidates, or unexpected mismatches)")
    print("=" * 78)
    for r in no_evidence_rows:
        if r["bucket"] != "NEEDS_REVIEW":
            continue
        print(f"\n[{r['document_id']}/{r['claim_id']}] {r['reason']}")
        print(f"  citation_extracted: {r['citation_extracted']}")
        print(f"  claim_text: {r['claim_text'][:200]}")

    print(f"\nWrote {outputs / 'no_evidence_diagnosis.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
