#!/usr/bin/env python3
"""
Replays the 6 real, previously-blocked (correction_scope_violation)
natural-data correction attempts from the 50-case GPU experiment through
the NEW "assertion_spans" structured scope check
(config.correction.atomic_scope_check="assertion_spans"), using the REAL
original/regenerated text Qwen already produced.

Supersedes nothing — scripts/replay_atomic_scope_check.py (Phase 1,
assertion_text-only mode) and its outputs are untouched. This script adds
the "assertion_spans" mode (Phase 2 of this task: the "respectively"
pattern) to the same replay, producing new, separately-named outputs.

NO GPU, NO Qwen call, NO re-verification — pure deterministic replay of
`pipeline._scope_violation()` against already-genuinely-generated text.

READ-ONLY: outputs/natural_candidates_50_gpu_*.jsonl only read. Writes
outputs/atomic_scope_check_replay_v2.{md,json}.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_PROTOTYPE_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROTOTYPE_ROOT.parent.parent))
sys.path.insert(0, str(_PROTOTYPE_ROOT))

from src import claim_parser, pipeline


def build_claims(generated_text: str) -> list[dict]:
    claims = claim_parser.extract_claims(generated_text)
    return [
        {"claim_id": c.claim_id, "claim_text": c.claim_text, "assertion_text": c.assertion_text,
         "assertion_spans": list(c.assertion_spans),
         "citation": c.citation_extracted.as_dict() if c.citation_extracted else None}
        for c in claims
    ]


def main() -> int:
    outputs = _PROTOTYPE_ROOT / "outputs"
    corrections = [json.loads(l) for l in
                   (outputs / "natural_candidates_50_gpu_corrections_detail.jsonl").read_text(encoding="utf-8").splitlines()]

    scope_violations = [r for r in corrections if r["status"] == "correction_scope_violation"]
    print(f"Replaying {len(scope_violations)} real scope-violation attempts "
          f"through legacy / assertion_text / assertion_spans...", flush=True)

    results = []
    for r in scope_violations:
        doc_id = r["document_id"]
        target_id = r["triggered_for_claim_id"]
        original_text = r["original_field_text"]
        regenerated_text = r["regenerated_text"]

        claims = build_claims(original_text)
        by_id = {c["claim_id"]: c for c in claims}
        target = by_id.get(target_id)

        legacy_v = pipeline._scope_violation(claims, target_id, regenerated_text,
                                              use_assertion_text=False, use_assertion_spans=False)
        text_v = pipeline._scope_violation(claims, target_id, regenerated_text,
                                            use_assertion_text=True, use_assertion_spans=False)
        spans_v = pipeline._scope_violation(claims, target_id, regenerated_text,
                                             use_assertion_text=True, use_assertion_spans=True)

        target_had_respectively_spans = bool(
            target and len(target["assertion_spans"]) > 1
        )

        results.append({
            "document_id": doc_id, "target_claim_id": target_id,
            "target_citation": target["citation"] if target else None,
            "target_had_respectively_spans": target_had_respectively_spans,
            "target_assertion_spans": target["assertion_spans"] if target else None,
            "legacy_violation": legacy_v,
            "assertion_text_violation": text_v,
            "assertion_spans_violation": spans_v,
            "unblocked_by_assertion_spans": legacy_v and not spans_v,
            "original_field_text": original_text,
            "regenerated_text": regenerated_text,
        })
        outcome = "UNBLOCKED (new, assertion_spans)" if (legacy_v and not spans_v) else (
            "still blocked" if spans_v else "already unblocked by assertion_text alone"
        )
        print(f"  {doc_id}/{target_id}: legacy={legacy_v} assertion_text={text_v} "
              f"assertion_spans={spans_v} -> {outcome}", flush=True)

    n_unblocked_spans = sum(1 for r in results if r["unblocked_by_assertion_spans"])
    n_still_blocked = sum(1 for r in results if r["assertion_spans_violation"])

    (outputs / "atomic_scope_check_replay_v2.json").write_text(json.dumps({
        "n_scope_violations_replayed": len(results),
        "n_unblocked_by_assertion_spans_beyond_assertion_text": n_unblocked_spans,
        "n_still_blocked_under_assertion_spans": n_still_blocked,
        "results": results,
    }, indent=2), encoding="utf-8")

    md = [
        "# assertion_spans (\"respectively\") Scope-Check Replay — 6 real natural scope violations",
        "",
        "_Generated by scripts/replay_assertion_spans_check.py — no GPU, no new Qwen call;",
        "replays real, already-captured original/regenerated text from the 50-case GPU",
        "experiment through legacy / assertion_text (Phase 1) / assertion_spans (Phase 2)._",
        "",
        f"**{n_unblocked_spans}/{len(results)} real scope violations newly unblocked by "
        f"assertion_spans** (beyond what assertion_text alone already achieved — 0/6, see "
        f"outputs/atomic_scope_check_replay.md).",
        f"**{n_still_blocked}/{len(results)} remain correctly blocked** even under assertion_spans.",
        "",
        "| document | target | citation | had respectively spans? | legacy | assertion_text | assertion_spans | outcome |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in results:
        cit = r["target_citation"]
        cit_str = f"{cit['provision_type']} {cit['provision_number']}" if cit else "?"
        outcome = "**UNBLOCKED**" if r["unblocked_by_assertion_spans"] else (
            "still blocked" if r["assertion_spans_violation"] else "already OK"
        )
        md.append(f"| `{r['document_id']}` | {r['target_claim_id']} | {cit_str} | "
                   f"{r['target_had_respectively_spans']} | {r['legacy_violation']} | "
                   f"{r['assertion_text_violation']} | {r['assertion_spans_violation']} | {outcome} |")

    (outputs / "atomic_scope_check_replay_v2.md").write_text("\n".join(md) + "\n", encoding="utf-8")

    print(f"\n{n_unblocked_spans}/{len(results)} newly unblocked by assertion_spans, "
          f"{n_still_blocked}/{len(results)} still blocked.")
    print(f"Wrote {outputs / 'atomic_scope_check_replay_v2.json'}")
    print(f"Wrote {outputs / 'atomic_scope_check_replay_v2.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
