#!/usr/bin/env python3
"""
Replays the 6 real, previously-blocked (correction_scope_violation)
natural-data correction attempts from the 50-case GPU experiment
(outputs/natural_candidates_50_gpu_corrections_detail.jsonl) through the
NEW atomic-claim scope check (config.correction.atomic_scope_check=true),
using the REAL original/regenerated text Qwen already produced.

NO GPU, NO Qwen call, NO re-verification — this is a pure, deterministic
replay of `pipeline._scope_violation()` against text that was already
genuinely generated. This is the scientifically correct way to measure
"would the atomic-claim fix have unblocked this correction" without
burning GPU time to re-derive text the corrector already produced once.

claim_text/citation data is RE-EXTRACTED fresh from the committed
generated_field.text using the CURRENT claim_parser (the atomic-claim
splitter did not exist, in its current form, when that GPU run was made),
not read back from the stale assertion_text values already stored in
natural_candidates_50_gpu_labeled.jsonl.

READ-ONLY: outputs/natural_candidates_50_gpu_*.jsonl are only read.
Nothing is regenerated or overwritten. Writes a new report,
outputs/atomic_scope_check_replay.md, and a raw JSON,
outputs/atomic_scope_check_replay.json.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_PROTOTYPE_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROTOTYPE_ROOT.parent.parent))
sys.path.insert(0, str(_PROTOTYPE_ROOT))

from src import claim_parser, pipeline


def build_claims(generated_text: str) -> list[dict]:
    claims = claim_parser.extract_claims(generated_text)
    return [
        {"claim_id": c.claim_id, "claim_text": c.claim_text, "assertion_text": c.assertion_text,
         "citation": c.citation_extracted.as_dict() if c.citation_extracted else None}
        for c in claims
    ]


def main() -> int:
    outputs = _PROTOTYPE_ROOT / "outputs"
    corrections = [json.loads(l) for l in
                   (outputs / "natural_candidates_50_gpu_corrections_detail.jsonl").read_text(encoding="utf-8").splitlines()]
    labeled_by_doc = {}
    for line in (outputs / "natural_candidates_50_gpu_labeled.jsonl").read_text(encoding="utf-8").splitlines():
        rec = json.loads(line)
        labeled_by_doc[rec["document_id"]] = rec

    scope_violations = [r for r in corrections if r["status"] == "correction_scope_violation"]
    print(f"Replaying {len(scope_violations)} real scope-violation attempts...", flush=True)

    results = []
    for r in scope_violations:
        doc_id = r["document_id"]
        target_id = r["triggered_for_claim_id"]
        original_text = r["original_field_text"]
        regenerated_text = r["regenerated_text"]

        claims = build_claims(original_text)
        by_id = {c["claim_id"]: c for c in claims}
        target = by_id.get(target_id)

        legacy_violation = pipeline._scope_violation(claims, target_id, regenerated_text, use_assertion_text=False)
        atomic_violation = pipeline._scope_violation(claims, target_id, regenerated_text, use_assertion_text=True)

        target_atomic_span = target["assertion_text"] if target else None
        target_is_atomic = bool(target and target["assertion_text"] != target["claim_text"])

        results.append({
            "framing": r["framing"], "document_id": doc_id, "target_claim_id": target_id,
            "target_citation": target["citation"] if target else None,
            "target_had_atomic_span": target_is_atomic,
            "legacy_scope_violation": legacy_violation,
            "atomic_scope_violation": atomic_violation,
            "unblocked_by_atomic_fix": legacy_violation and not atomic_violation,
            "original_field_text": original_text,
            "regenerated_text": regenerated_text,
        })
        status = "UNBLOCKED" if (legacy_violation and not atomic_violation) else (
            "still blocked (legitimately)" if atomic_violation else "already not a violation??"
        )
        print(f"  {doc_id}/{target_id}: legacy={legacy_violation} atomic={atomic_violation} -> {status}", flush=True)

    n_unblocked = sum(1 for r in results if r["unblocked_by_atomic_fix"])
    n_still_blocked = sum(1 for r in results if r["atomic_scope_violation"])

    (outputs / "atomic_scope_check_replay.json").write_text(json.dumps({
        "n_scope_violations_replayed": len(results),
        "n_unblocked_by_atomic_fix": n_unblocked,
        "n_still_blocked": n_still_blocked,
        "results": results,
    }, indent=2), encoding="utf-8")

    md = [
        "# Atomic-Claim Scope-Check Replay — 6 real natural scope violations",
        "",
        "_Generated by scripts/replay_atomic_scope_check.py — no GPU, no new Qwen call;",
        "replays real, already-captured original/regenerated text from the 50-case GPU",
        "experiment through the new `atomic_scope_check=true` logic. Claim data is",
        "re-extracted fresh from the current (fixed) claim_parser, not read back from",
        "the stale assertion_text values already on disk._",
        "",
        f"**{n_unblocked}/{len(results)} real scope violations are unblocked by the atomic-claim fix.**",
        f"**{n_still_blocked}/{len(results)} remain correctly blocked** (the edit genuinely touched",
        "content outside the flagged claim's own atomic span, or no safe split existed for",
        "this sentence shape).",
        "",
        "| document | target claim | citation | had atomic span? | legacy | atomic | outcome |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in results:
        cit = r["target_citation"]
        cit_str = f"{cit['provision_type']} {cit['provision_number']}" if cit else "?"
        outcome = "**UNBLOCKED**" if r["unblocked_by_atomic_fix"] else (
            "still blocked" if r["atomic_scope_violation"] else "already passed"
        )
        md.append(f"| `{r['document_id']}` | {r['target_claim_id']} | {cit_str} | "
                   f"{r['target_had_atomic_span']} | {r['legacy_scope_violation']} | "
                   f"{r['atomic_scope_violation']} | {outcome} |")

    (outputs / "atomic_scope_check_replay.md").write_text("\n".join(md) + "\n", encoding="utf-8")

    print(f"\n{n_unblocked}/{len(results)} unblocked, {n_still_blocked}/{len(results)} still blocked.")
    print(f"Wrote {outputs / 'atomic_scope_check_replay.json'}")
    print(f"Wrote {outputs / 'atomic_scope_check_replay.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
